desc emp;
desc dept;
select * From DEPT;
select deptno , loc From dept;
select ename, sal From emp;
select ename, sal, sal+300 From emp;
select ename,sal, comm, sal+comm From emp;
select ename, sal, NVL(comm,0), sal+NVL(comm,0) From emp;
select deptno From emp;
select DISTINCT deptno From emp;
SELECT ename, job, deptno From emp Where ename ='JAMES';
select ename, deptno From emp Where deptno=30;
select * From emp Where deptno=30;
Select ename, sal From emp Where sal > 1000 and sal < 1500;
select empno, ename, sal, mgr From emp Where mgr IN(7902,7566,7788);
select ename From emp Where ename Like 's%';
select ename, mgr From emp Where mgr is NULL;
select empno, ename, job, sal From Emp where sal>=1100 and job='CLERK';
select empno, ename, job, sal From Emp where sal>=1100 or job='CLERK';
select ename, job From emp Where job Not IN ('CLERK', 'MANAGER', 'ANALYST');
select ename, job, deptno, hiredate From emp Order By hiredate;
select ename, job, deptno, hiredate From emp Order By hiredate desc;
select ename, deptno, sal From emp Order By deptno, sal Desc;

select ename, job, hiredate, empno From emp;
select ename, sal From emp Where sal > 2850;
select DISTINCT job From emp;
select ename, sal From emp Where sal < 1500 or sal > 2850;
select ename, job From emp Where mgr is NULL;
select ename, sal, comm From emp Where comm is Not NULL Order By sal Desc, comm Desc;
select ename From emp Where ename like '__A%';